#pragma once

#include <freezone/protocol/freezone_operations.hpp>

#include <freezone/chain/evaluator.hpp>

namespace freezone { namespace chain {

using namespace freezone::protocol;

freezone_DEFINE_EVALUATOR( account_create )
freezone_DEFINE_EVALUATOR( account_create_with_delegation )
freezone_DEFINE_EVALUATOR( account_update )
freezone_DEFINE_EVALUATOR( account_update2 )
freezone_DEFINE_EVALUATOR( transfer )
freezone_DEFINE_EVALUATOR( transfer_to_vesting )
freezone_DEFINE_EVALUATOR( witness_update )
freezone_DEFINE_EVALUATOR( account_witness_vote )
freezone_DEFINE_EVALUATOR( account_witness_proxy )
freezone_DEFINE_EVALUATOR( withdraw_vesting )
freezone_DEFINE_EVALUATOR( set_withdraw_vesting_route )
freezone_DEFINE_EVALUATOR( comment )
freezone_DEFINE_EVALUATOR( comment_options )
freezone_DEFINE_EVALUATOR( delete_comment )
freezone_DEFINE_EVALUATOR( vote )
freezone_DEFINE_EVALUATOR( vote2 )
freezone_DEFINE_EVALUATOR( custom )
freezone_DEFINE_EVALUATOR( custom_json )
freezone_DEFINE_EVALUATOR( custom_binary )
freezone_DEFINE_EVALUATOR( pow )
freezone_DEFINE_EVALUATOR( pow2 )
freezone_DEFINE_EVALUATOR( feed_publish )
freezone_DEFINE_EVALUATOR( convert )
freezone_DEFINE_EVALUATOR( limit_order_create )
freezone_DEFINE_EVALUATOR( limit_order_cancel )
freezone_DEFINE_EVALUATOR( report_over_production )
freezone_DEFINE_EVALUATOR( limit_order_create2 )
freezone_DEFINE_EVALUATOR( escrow_transfer )
freezone_DEFINE_EVALUATOR( escrow_approve )
freezone_DEFINE_EVALUATOR( escrow_dispute )
freezone_DEFINE_EVALUATOR( escrow_release )
freezone_DEFINE_EVALUATOR( claim_account )
freezone_DEFINE_EVALUATOR( create_claimed_account )
freezone_DEFINE_EVALUATOR( request_account_recovery )
freezone_DEFINE_EVALUATOR( recover_account )
freezone_DEFINE_EVALUATOR( change_recovery_account )
freezone_DEFINE_EVALUATOR( transfer_to_savings )
freezone_DEFINE_EVALUATOR( transfer_from_savings )
freezone_DEFINE_EVALUATOR( cancel_transfer_from_savings )
freezone_DEFINE_EVALUATOR( decline_voting_rights )
freezone_DEFINE_EVALUATOR( reset_account )
freezone_DEFINE_EVALUATOR( set_reset_account )
freezone_DEFINE_EVALUATOR( claim_reward_balance )
freezone_DEFINE_EVALUATOR( claim_reward_balance2 )
freezone_DEFINE_EVALUATOR( delegate_vesting_shares )
freezone_DEFINE_EVALUATOR( witness_set_properties )
freezone_DEFINE_EVALUATOR( SST_setup )
freezone_DEFINE_EVALUATOR( SST_setup_emissions )
freezone_DEFINE_EVALUATOR( SST_setup_ico_tier )
freezone_DEFINE_EVALUATOR( SST_set_setup_parameters )
freezone_DEFINE_EVALUATOR( SST_set_runtime_parameters )
freezone_DEFINE_EVALUATOR( SST_create )
freezone_DEFINE_EVALUATOR( SST_contribute )
freezone_DEFINE_EVALUATOR( create_proposal )
freezone_DEFINE_EVALUATOR( update_proposal_votes )
freezone_DEFINE_EVALUATOR( remove_proposal )

} } // freezone::chain
